name: Build

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.PRIVATE_KEY_TEAL_HERCULES }}

      - name: SSH ping in order to register "known host"
        run: ssh -o "StrictHostKeyChecking no" root@hercules.teal.ooo whoami

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            substituters        = https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - name: Deploy Dry Activate
        if: ${{ github.ref != 'refs/heads/main' }}
        run: nix develop --command make deploy-dry

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        run: nix develop --command make deploy
