name: Build

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_TEAL_BUILD }}

      - name: SSH ping in order to register "known host"
        run: ssh -o "StrictHostKeyChecking no" root@65.21.251.123 whoami

      # - name: Check NixOS version
      #   id: nixos-version
      #   run: ssh root@65.21.251.123 nixos-version

      # - name: Maybe install NixOS
      #   if: failure() && steps.nixos-version.outcome == 'failure'
      #   run: echo ok

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            substituters        = https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - name: Deploy
        run: make deploy

      # - name: Deploy Dry Activate
      #   if: ${{ github.ref != 'refs/heads/main' }}
      #   run: make deploy-dry-activate

      # - name: Deploy
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   run: make deploy
